# Generated by Django 2.2.6 on 2019-11-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_grade',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
