# Generated by Django 2.2.7 on 2019-11-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelnum', models.TextField()),
                ('productName', models.TextField()),
                ('retailer', models.TextField()),
                ('link', models.TextField()),
                ('thumbnail_url', models.TextField(null=True)),
                ('price', models.TextField()),
                ('reviewnum', models.TextField(null=True)),
                ('rating', models.TextField(null=True)),
            ],
        ),
    ]
