# Generated by Django 2.2.6 on 2019-11-05 05:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191104_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='articles/%Y/%m/%d'),
        ),
    ]
